# Project for github

trigger:
- develop

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Github
    displayName: Repository Creation
    pool:
      vmImage: $(vmImageName)

    steps:

# steps:
# - script: Creating a new repository in github
#   displayName: 'REPO'

    - task: Bash@3
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        targetType: 'inline'
        script: |
          echo "Hello!"
          source ~/.secrets.sh
          ./create_repos.sh
